export const REGISTER_ACTION_INITIATED = 'REGISTER_ACTION_INITIATED';
export const REGISTER_ACTION_SUCCESS = 'REGISTER_ACTION_SUCCESS';
export const REGISTER_ACTION_FAILURE = 'REGISTER_ACTION_FAILURE';
